version: '3'

services:
  harja-kontti:
    image: circleci-testi:latest
    stdin_open: true
    tty: true
    links:
      - possu
  possu:
    image: solita/harjadb:centos-9.5
    stdin_open: true
    tty: true
    ports:
      - "5432:5432"