# build-workflowsta minimoitu versio trivy-lis√§yksin
name: 'Harja: Build & trivy test'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - trivy-testi

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    # README: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      # Contents read lupaa tarvitaan checkout actionissa
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Huom: Build-action tarvitsee testitietokannan taustalle ennen buildin ajoa
      - name: Build Harja Uberjar
        uses: ./.github/actions/build-harja-app
        with:
          build-laadunseuranta: 'false'

      - name: Docker build
        run: docker build -t harja-app:${{ github.sha }} --file aws/fargate/Dockerfile .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@2b6a709cf9c4025c5438138008beaddbb02086f0
        with:
          image-ref: 'harja-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
